name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag xpvit/spring-boot-jre:amazoncorretto-11
    - name: Docker hub login
      run: docker login --username xpvit  -p ${{ DOCKER_HUB_TOKEN }}
    - name: Publish the Docker image
      run: docker push xpvit/spring-boot-jre:amazoncorretto-11