name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag -t xp-vit/spring-boot-jre:amazoncorretto-11
    - name: Publish the Docker image
      run: docker push xp-vit/spring-boot-jre:amazoncorretto-11